### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by jbkr** [jbkr/jbkrBioWeb#2]
Links only send to top of page rather than to destination in code. Layout bug?

**Comment by jbkr** [comment]
GitHub link broken too.

**Comment by jbkr** [comment]
Looks like a problem with DNS redirect... uh-oh.

**Comment by Trixxr** [comment]
Roger - I will look into this immediately. Sounds like a error 233 - but it all depends on the condition of the mainframe

**Comment by jbkr** [comment]
You do know there is an unsubscribe from issue button right?

**Comment by Trixxr** [comment]
But how would I know what issues to allocate my time towards? You never tell me in real life, James.


Best Regards
Anders Antoft Schou

Trixxr@Trixxr.com
+45 31 34 31 98
www.Trixxr.com

**Comment by jbkr** [comment]
I fixed it anyway.
